services:
  db:
    image: postgres:15-alpine
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data: /var/lib/postgresql/data
    network:
      - transcoder_net

  minio:
    image: minio/minio
    container_name: minio_service
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes: 
      - minio_data:/data
    network:
      - transcoder_net
  
  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    network:
      - transcoder_net

  api:
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    container_name: api_service
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - minio
    network:
      - transcoder_net

  worker:
    build:
      context: ..
      dockerfile: services/worker/Dockerfile
    container_name: worker_service
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - minio
    network:
      - transcoder_net
network:
  transcoder_net:
    driver: bridge
volumes:
  minio_data:
  postgres_data: