services:
  db:
    image: postgres:15-alpine
    container_name: postgres_service
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcoder_net

  minio:
    image: minio/minio
    container_name: minio_service
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes: 
      - minio_data:/data
    networks:
      - transcoder_net
  
  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - transcoder_net

  api:
    build:
      context: ..
      dockerfile: services/api/Dockerfile
    container_name: api_service
    ports:
      - "3000:3000"
    cpus: 1.0           
    mem_limit: 1024mb
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ../services/api/temp/uploads:/app/services/api/temp/uploads
      - ../infra/migrations:/app/infra/migrations
      - ../shared:/app/shared
    networks:
      - transcoder_net
    develop:
      watch:
        - action: sync
          path: ../services/api
          target: /app/services/api
          ignore:
            - node_modules
        - action: sync
          path: ../shared
          target: /app/shared
        - action: rebuild
          path: ../package.json

  worker:
    build:
      context: ..
      dockerfile: services/worker/Dockerfile
    cpus: 1         
    mem_limit: 1024mb
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ../services/worker/temp/raw:/app/services/worker/temp/raw
      - ../services/worker/temp/processed:/app/services/worker/temp/processed
      - ../shared:/app/shared
    networks:
      - transcoder_net
    develop:
      watch:
        - action: sync
          path: ../services/worker
          target: /app/services/worker
          ignore:
            - node_modules
        - action: sync
          path: ../shared
          target: /app/shared
        - action: rebuild
          path: ../package.json
networks:
  transcoder_net:
    driver: bridge
volumes:
  minio_data:
  postgres_data: